- name: Build with PyInstaller
      run: |
        # 这一步生成 exe
        pyinstaller --onefile --noconsole --name TwstOverlay main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TwstOverlay-Package
        path: |
          dist/TwstOverlay.exe
          data.json
